CREATE DATABASE doingsdone
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(128) NOT NULL UNIQUE,
	name VARCHAR(128) NOT NULL,
	password CHAR(128) NOT NULL 
);

CREATE TABLE tasks (
	id INT AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status TINYINT UNSIGNED NOT NULL DEFAULT 0,
	name VARCHAR(128) NOT NULL,
	file VARCHAR(128), 
	dt_do TIMESTAMP,
	user_id INT NOT NULL,
	project_id INT NOT NULL,
	INDEX (user_id),
	INDEX (project_id)
);	

CREATE TABLE projects (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(128) NOT NULL UNIQUE,
	user_id INT NOT NULL,
	INDEX (user_id)
);

